### ISSUE TITLE
IDE: jump to collaborator's cursor

### ISSUE THREAD

**Issue by foresthoffman** [codercom/features#65] opened 2018-08-15 15:38 UTC
**Is your feature request related to a problem? Please describe.**
When files become large (1000+ lines), finding a collaborator's cursor can be difficult.

**Describe the solution you'd like**
The ability to jump to a collaborator's cursor in a file they are sharing.

**Comment by deansheather** [comment] 2018-08-17 05:46
Duplicate of #59.

**Closed** 2019-01-10 22:11 UTC
Labels: enhancement, tracking
