### ISSUE TITLE
Downloading in the IDE

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/features#145] opened 2018-11-13 19:17 UTC
**Is your feature request related to a problem? Please describe.**
Users want to be able to export their files into iCloud and download files from their projects.

**Describe the solution you'd like**
Make it so that users have a clickable button or menu option to download files. This would be the first step to exporting files.

```zendesk 1442```

**Comment by deansheather** [comment] 2018-11-26 14:32
Duplicate of #144.

**Closed by deansheather** 2018-11-26 14:32 UTC
Labels: enhancement, tracking
