### ISSUE TITLE
Have other versions of Python available to mount

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/features#114] opened 2018-09-06 15:18 UTC
**Is your feature request related to a problem? Please describe.**
We have several users who work with Python. Different dependencies only work with certain versions. It would make their experience better if we made several versions of Python available for them to choose from and mount. Uninstalling 3.7 and reinstalling can be tedious.

**Describe the solution you'd like**
Since there are several versions being used, we could start by adding a couple of the more popular versions and add on from there as necessary.

**Comment by pokemonlover1234** [comment] 2018-09-06 18:44
Duplicate of bugs/#64?

**Closed** 2018-11-08 13:48 UTC
Labels: enhancement, tracking
