### ISSUE TITLE
Allow users to leave collaborations they're invited to join

### ISSUE THREAD

**Issue by jaymeramsay** [codercom/features#115] opened 2018-09-06 21:52 UTC
**Is your feature request related to a problem? Please describe.**
Right now, users can't leave collaborations on their own. When they try to delete the project from their dashboard, it says they don't have permission to do so. We should make an option for them to leave these projects at will.

**Describe the solution you'd like**
A delete button on the collaborative project that allows the user to leave. We might also shoot the owner of the project a message informing them of the departure.

**Additional context**
`via discord, user lilrex`

**Comment by pokemonlover1234** [comment] 2018-09-06 22:04
Duplicate of #35?

**Comment by Multishifties** [comment] 2018-12-20 16:37
UPDATE: I have an open PR for this.

**Comment by Multishifties** [comment] 2019-02-04 21:49
UPDATE: And Collaboration is now removed. This Issue is no longer relevant. @nol166 Please close this issue.

**Comment by nol166** [comment] 2019-02-05 17:55
Not relevant. Closing.

**Closed by nol166** 2019-02-05 17:55 UTC
Labels: enhancement, tracking
